### ISSUE TITLE
[ci/cd] Deploy Docker Image

### ISSUE THREAD

**Issue by jeffersonroth** [jeffersonroth/jjrf-data-reliability-book#30]
create a custom Docker image that includes mdbook and all the necessary plugins pre-installed. This approach can significantly reduce the build time for your GitHub Actions workflow by avoiding the repeated installation of these tools on every run. Here's how you can do it:

Step 1: Create a Dockerfile
First, you need to create a Dockerfile that specifies how to build your custom Docker image. This Dockerfile will start from a Rust base image, install mdbook and all the desired mdbook plugins, and set up any other necessary environment configurations.

```Dockerfile
# Start from the official Rust image
FROM rust:latest

# Install mdBook and its plugins
RUN cargo install mdbook \
    && cargo install mdbook-toc \
    && cargo install mdbook-catppuccin \
    && cargo install mdbook-mermaid \
    && cargo install mdbook-plantuml \
    && cargo install mdbook-footnote \
    && cargo install mdbook-emojicodes

# Set the working directory
WORKDIR /usr/src/book

# By default, just keep the container running
CMD ["sleep", "infinity"]
```
Step 2: Build and Push the Docker Image
After creating the Dockerfile, you need to build the Docker image and push it to a Docker registry like Docker Hub or GitHub Container Registry.

```bash
# Build your Docker image
docker build -t yourusername/mdbook-environment .

# Push the image to a registry
docker push yourusername/mdbook-environment
```

Replace yourusername with your Docker Hub username or your GitHub username if you're using GitHub Container Registry. Make sure you're logged in to the respective registry in your terminal before pushing the image.

Step 3: Use the Custom Docker Image in GitHub Actions
With the custom Docker image pushed to a registry, you can now use it in your GitHub Actions workflow. Modify your workflow file to use this image instead of running on the ubuntu-latest runner and installing dependencies every time.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: yourusername/mdbook-environment:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with mdBook
        run: |
          mdbook build
        working-directory: /usr/src/book

      # Other steps as needed...
```

In this configuration, the build job runs in a container based on your custom Docker image. The actions/checkout@v4 step checks out your repository into the container, and then the mdbook build command is run within the container environment that already has mdbook and all necessary plugins installed.

This setup should lead to faster execution times for your workflow, as the time-consuming installation steps are eliminated.
